blogger_api:
    type: rest
    resource: "@BloggerApiBundle/Resources/config/routing.yml"
    prefix: /api/v1

blogger_user:
    resource: "@BloggerUserBundle/Resources/config/routing.yml"
    prefix:   /

blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
